# preload = ~/Pictures/Wallpapers/bythelake.png

wallpaper {
    monitor = eDP-1
    path = ~/Pictures/Wallpapers/bythelake.png
}

splash = false
# wallpaper = DP-3,~/Pictures/Wallpapers/bythelake.png
# wallpaper = DP-4,~/Pictures/Wallpapers/bythelake.png
