[mgr]
show_hidden = true

[opener]
image = [
    { run = 'qimgv "$@"', desc = "View with qimpv" },
    { run = 'gimp "$@"', desc = "Edit with GIMP" },
]

[open]
rules = [
    { mime = "image/*", use = "image" },
]
